riocli/parameter/__init__.py
riocli/parameter/apply.py
riocli/parameter/delete.py
riocli/parameter/diff.py
riocli/parameter/download.py
riocli/parameter/list.py
riocli/parameter/upload.py
riocli/parameter/utils.py

This PR updates the parameter commands with the new spinner and replaces literals with constants wherever applicable.
[![asciicast](https://asciinema.org/a/594423.svg)](https://asciinema.org/a/594423)

✨ feat(parameter): adds spinner and constants 

---

riocli/organization/select.py

This PR adds the option to set the project non-interactively while selecting an organization.
```
rio organization select org-name --project project-name
```

✨ feat(organiztion): adds option to set project non-interactively

---

riocli/organization/__init__.py
riocli/organization/list.py
riocli/organization/select.py

This command updates the `organization` command with constants and minor refactors.

🔨 refactor(organization): updates implementation to use constants

---

riocli/deployment/util.py
riocli/network/util.py

This commit brings uniformity in error message of rio inspect when resource is invalid.
Demo: https://asciinema.org/a/Sef26bU4t3q4cd1OfervmHiBX

:bug:  fix: improves inspect invalid deployment and network error message

---

riocli/project/create.py
riocli/project/delete.py
riocli/project/features/__init__.py
riocli/project/features/vpn.py
riocli/project/inspect.py
riocli/project/list.py
riocli/project/model.py
riocli/project/select.py
riocli/project/util.py

This PR updates the spinner in the project command and replaces literals with constants wherever applicable.

✨ feat(project): adds yaspin implementation to project commands

---

riocli/vpn/connect.py
riocli/vpn/disconnect.py
riocli/vpn/ping.py
riocli/vpn/status.py
riocli/vpn/util.py

This PR adds spinner in the vpn commands and refactors a part of the implementation.

✨ feat(vpn): adds spinner and refactors implementation

---

riocli/static_route/__init__.py
riocli/static_route/create.py
riocli/static_route/delete.py
riocli/static_route/inspect.py
riocli/static_route/list.py
riocli/static_route/model.py
riocli/static_route/open.py
riocli/static_route/util.py

This PR replaces all `click_spinner` implementations with `yaspin` spinner.
[![asciicast](https://asciinema.org/a/bQy3SZHQdKYbCCCfjwdAXqw2Y.svg)](https://asciinema.org/a/bQy3SZHQdKYbCCCfjwdAXqw2Y)
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1096469185)

✨ feat(static-route): updates spinner and other implementations

---

riocli/auth/__init__.py
riocli/auth/login.py
riocli/auth/logout.py
riocli/auth/refresh_token.py
riocli/auth/staging.py
riocli/auth/status.py
riocli/auth/token.py
riocli/auth/util.py

This PR updates the spinner in the `auth` command and adds minor refactors.
(cherry picked from commit faa774537f8e65d319df1c44caac1efa09896087)

✨ feat(auth): updates spinner and refactors existing code

---

riocli/organization/users.py
riocli/usergroup/model.py

This PR will have all the bug fixes reported for the upcoming release of the CLI.

🐛 fix: CLI Bug Fixes

---

riocli/constants/symbols.py

Updates the symbols to use newer emojis
```
INFO = 'ℹ️'
ERROR = '❌'
SUCCESS = '✅'
WARNING = '⚠️'
WAITING = '⏳'
```

🔨 refactor(constants): updates the symbols to emojis

---

riocli/usergroup/model.py

This PR fixes the issue where admins were being removed with every usergroup update.

fix(usergroup): update usergroup removes active admins

---

.github/workflows/python-compatibility.yml
riocli/deployment/execute.py
riocli/device/vpn.py
riocli/network/delete.py
riocli/parameter/apply.py
riocli/parameter/delete.py
riocli/parameter/upload.py
riocli/utils/__init__.py
riocli/utils/spinner.py
setup.py

🎉 release: v4.1.0

---

riocli/usergroup/inspect.py

Printing the JSON response from the usergroup API doesn't make a lot of sense in the CLI and makes it challenging for the users to build a manifest out of it. This fix corrects the output and transform it to rio manifest construct.
> Wrike: https://www.wrike.com/open.htm?id=1173432945

🐛 fix(usergroup): outputs a rio manifest construct in inspect

---

riocli/usergroup/inspect.py

🚑 hotfix: v4.2.1

---

riocli/vpn/connect.py

🐛 fix(vpn): hides spinner when asked for password

---

riocli/project/features/vpn.py

Recently, the project update API was updated to reflect the state as sent in the request payload. The vpn command in project had the older implementation and we forgot to update it when the project update API was changed. This issue can lead to serious loss of project info if not fixed in time. This commit corrects that by first fetching the project and updating it with the new values before passing it as the payload for update.
For example, created a new project with a few labels or add one or more users or groups. Then run `rio project features vpn {PROJECT_NAME} true`. You will notice that in `rio project inspect {PROJECT_NAME}`, the labels or users are gone except the admins.
However, with the fix, things should be fine.

fix(project): fixes project update with vpn state

---

riocli/deployment/model.py
riocli/device/deployment.py
riocli/jsonschema/schemas/deployment-schema.yaml
riocli/jsonschema/schemas/secret-schema.yaml
riocli/jsonschema/validate.py
riocli/parameter/apply.py
riocli/parameter/download.py
riocli/parameter/list.py
riocli/parameter/upload.py
riocli/parameter/utils.py
riocli/project/features/vpn.py
riocli/utils/__init__.py
riocli/utils/cache.py
riocli/v2client/client.py

Please refer to the Wrike tickets tagged in the commit messages.

🐛 fix: miscellaneous bug fixes around parameters, jsonschem and device

---

riocli/auth/staging.py
riocli/auth/util.py
riocli/jsonschema/schemas/deployment-schema.yaml
riocli/jsonschema/schemas/package-schema.yaml

This commit improves the reporting in the `rio auth environment` command to better the overall user experience.

🔨 refactor(auth): improves reporting in the auth environment command

---

riocli/deployment/delete.py
riocli/deployment/update.py
riocli/deployment/util.py
riocli/device/delete.py
riocli/device/util.py
riocli/package/delete.py
riocli/package/util.py
riocli/parameter/apply.py
riocli/utils/execute.py

This PR introduces batch or regex operations for the following commands
- `rio deployment delete`
- `rio deployment update`
- `rio package delete`
---
> Wrike: https://www.wrike.com/open.htm?id=1235227535

✨ feat: supports regex operations in various cli commands

---

riocli/apply/resolver.py
riocli/deployment/logs.py
riocli/disk/util.py
riocli/organization/utils.py
riocli/parameter/utils.py
riocli/utils/execute.py

🎉 release: v7.0.1

---

riocli/apply/parse.py
riocli/deployment/util.py
riocli/device/util.py
riocli/jsonschema/schemas/deployment-schema.yaml
riocli/package/util.py

🎉 release: v7.0.2

---

riocli/jsonschema/schemas/deployment-schema.yaml

🎉 release: v7.0.3

---

riocli/config/config.py
riocli/project/__init__.py
riocli/project/list.py
riocli/project/util.py
riocli/project/whoami.py
riocli/v2client/client.py

🎉 release: v7.1.0

---

riocli/apply/manifests/staticroute.yaml
riocli/jsonschema/schemas/static_route-schema.yaml
riocli/static_route/model.py
riocli/v2client/client.py

For more context: https://github.com/rapyuta-robotics/rapyuta_io/wiki/StaticRoute-IP-Whitelist

feat(static-route): add support for IP Whitelisting

---

riocli/v2client/client.py

This commit removes the list limit for v2 static routes API.

fix(v2client): increases static-route list limit

---

.github/workflows/gh-pages.yml
Pipfile
Pipfile.lock
docs/source/conf.py

```
→ act push -j deploy 
[Github Pages for Documentation/deploy] 🚀  Start image=catthehacker/ubuntu:act-22.04
INFO[0000] Parallel tasks (0) below minimum, setting to 1 
[Github Pages for Documentation/deploy]   🐳  docker pull image=catthehacker/ubuntu:act-22.04 platform= username= forcePull=true
INFO[0003] Parallel tasks (0) below minimum, setting to 1 
[Github Pages for Documentation/deploy]   🐳  docker create image=catthehacker/ubuntu:act-22.04 platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[Github Pages for Documentation/deploy]   🐳  docker run image=catthehacker/ubuntu:act-22.04 platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[Github Pages for Documentation/deploy] ⭐ Run Main actions/checkout@v2
[Github Pages for Documentation/deploy]   🐳 …
```

fix(docs): updates sphinx version and other dependencies

---

.github/workflows/gh-pages.yml
Pipfile
Pipfile.lock
docs/source/conf.py
riocli/auth/login.py
riocli/auth/util.py
riocli/project/util.py

🎉 release: v7.3.1

---

.github/workflows/gh-pages.yml

ci: uncomments gh-pages deploy step

---

riocli/project/whoami.py

An erroneous check led to wrong output. This fix removes the check.

fix(project): remove erroneous check from whoami

---

riocli/device/__init__.py
riocli/device/migrate.py
riocli/device/util.py

Check https://github.com/rapyuta-robotics/device_manager/pull/318 for more details.

feat(device): add support for migrating device between projects

---

riocli/__main__.py
riocli/apply/__init__.py
riocli/apply/explain.py
riocli/apply/parse.py
riocli/auth/login.py
riocli/auth/refresh_token.py
riocli/auth/staging.py
riocli/auth/token.py
riocli/auth/util.py
riocli/bootstrap.py
riocli/deployment/list.py
riocli/deployment/model.py
riocli/deployment/util.py
riocli/device/util.py
riocli/utils/__init__.py
setup.py

This pull request fixes miscellaneous bugs and implements some new features.

🐛 fix: miscellaneous bug fixes

---

riocli/configtree/etcd.py
riocli/configtree/export_keys.py
riocli/configtree/import_keys.py

🎉 release: v8.1.0

---

riocli/deployment/execute.py
riocli/deployment/util.py
riocli/device/execute.py
riocli/device/util.py
riocli/utils/execute.py

[demo](https://asciinema.org/a/xRMD6MXugenrDBTesvX5sMh82)

feat(deployment): execute commands on device deployments

---

riocli/v2client/client.py

Added the request-id as header with header name X-Request-ID.

feat(v2client): inject X-Request-ID in headers if REQUEST_ID in env

---

riocli/deployment/inspect.py

This pr is for guid support for deployment resource inspection. So we can also see the manifest for deprovisioned/stopped deployments.

fix(deployment): inspect deployment with guid

---

riocli/configtree/util.py
riocli/deployment/delete.py
riocli/network/delete.py
riocli/package/delete.py
riocli/package/util.py

This PR resolves multiple bugs identified during the v2 migration testing.

fix: miscellaneous CLI bugs

---

riocli/apply/parse.py
riocli/device/report.py
riocli/vpn/util.py
uv.lock

While adding the support for multiple value and secret files, I made the silly mistake of not performing a deep merge on the dicts. This PR fixes the issue.

fix(apply): deep merge secrets and values

---

riocli/apply/parse.py

Fixes a typo while merging secrets. 🤦🏼

fix(apply): secrets are not merged

---

.github/workflows/upload-appimage.yml
pyproject.toml
uv.lock

* https://github.com/rapyuta-robotics/rapyuta-io-sdk/pull/98

chore: bumps rapyuta-io sdk version

---

.github/workflows/upload-appimage.yml
pyproject.toml
riocli/apply/filters.py
riocli/device/report.py
riocli/organization/list.py
uv.lock

🎉 release: 9.2.0

---

pyproject.toml
riocli/apply/__init__.py
riocli/apply/filters.py
riocli/apply/manifests/deployment-nonros-device.yaml
riocli/apply/manifests/deployment.yaml
riocli/apply/manifests/device.yaml
riocli/apply/util.py
riocli/deployment/execute.py
riocli/device/execute.py
riocli/device/model.py
riocli/device/util.py
riocli/hwil/create.py
riocli/hwilclient/client.py
riocli/jsonschema/schemas/deployment-schema.yaml
riocli/jsonschema/schemas/device-schema.yaml
riocli/utils/execute.py
uv.lock

release: v9.5.0

---

riocli/device/delete.py

Resolves [AB#51601](https://dev.azure.com/rapyuta-robotics/3151e969-9eb7-4729-b4e8-8c659c416104/_workitems/edit/51601)

fix(device): return non-zero exit code if delete fails for atleast one device

---

riocli/vpn/connect.py

Resolves [AB#48205](https://dev.azure.com/rapyuta-robotics/3151e969-9eb7-4729-b4e8-8c659c416104/_workitems/edit/48205)

feat(vpn): support --force flag for vpn connect command

---

riocli/usergroup/model.py

This PR , handles the support for user email case insensitive.
Resolves https://github.com/rapyuta-robotics/rapyuta_io/issues/722

fix(usergroup): handle case-insensitive email support

---

pyproject.toml
uv.lock

Reference: https://github.com/pallets/click/issues/2897#issuecomment-2874680206

fix: pin click to 8.0.x

---

riocli/apply/parse.py

This PR, resolves https://github.com/rapyuta-robotics/rapyuta_io/issues/848. It now allow users to make values in form of jinja templates.
https://github.com/user-attachments/assets/ee07c263-2a5d-4479-b7c2-3dbb1773756b
Example that you can try: 
`hwil.yaml`
```yaml
{% for name in device_name %}
---
kind: "Device"
metadata:
name: "{{ name }}"
spec:
python: "3"
rosDistro: "melodic"
virtual:
enabled: True
arch: "amd64"
os: "ubuntu"
codename: "focal"
highperf: False
wait: True
expireAfter: '60h'
docker:
enabled: True
rosbagMountPath: "/opt/rapyuta/volumes/rosbag"
{% endfor %}
```
`values.json`
```json
{
"device_name": [
{% for i in range(1, 3) %}
"values-jinja{{ "%02d" % i }}"{% if not loop.last %},{% endif %}
{% endfor %}
]
}
```
`values.yaml` …

feat: jinja templating in values file

---

riocli/disk/delete.py
riocli/network/delete.py

Resolves rapyuta-robotics/rapyuta_io#860
Resolves rapyuta-robotics/rapyuta_io#861

fix(disk,network): fix delete command with --all flag

---

pyproject.toml

This PR updates the rapyuta-io-sdk version.

chore: update rapyuta-io-sdk

---

riocli/apply/manifests/package.yaml
riocli/jsonschema/schemas/package-schema.yaml

Partially resolves rapyuta-robotics/rapyuta_io#868

feat(packages): support specifying UID/GID per executable

---

pyproject.toml
riocli/device/execute.py
uv.lock

This pull request introduces improvements to the `execute_command` function in `riocli/device/execute.py`, focusing on better handling of command execution and error reporting. The changes include refining input validation, restructuring command composition, implementing retry logic, and enhancing feedback for failed executions.

:bug: fix(device): retry for late devices in async
