docs/source/index.rst
docs/source/usergroup.rst
riocli/apply/manifests/usergroup.yaml
riocli/apply/resolver.py
riocli/bootstrap.py
riocli/jsonschema/schemas/usergroup-schema.yaml
riocli/organization/utils.py
riocli/usergroup/__init__.py
riocli/usergroup/delete.py
riocli/usergroup/inspect.py
riocli/usergroup/list.py
riocli/usergroup/model.py
riocli/usergroup/util.py

This PR adds usergroup support in the CLI by introducing the `usergroup` sub-command.
We can `list`, `inspect` and `delete` usergroups using the sub-command while creation and updation happens via `apply` command.

✨ feat(usergroup): adds usergroup command

---

riocli/deployment/__init__.py
riocli/deployment/update.py

This commit introduces update deployment command that enables users to conveniently update existing deployments by providing deployment name or regex that can update multiple deployments
Demo: https://asciinema.org/a/F3rWES3S5IHffmfSbapDGVH84

✨ feat(deployment): adds command for updating deployment

---

riocli/usergroup/inspect.py

…ing usergroup with zero projects

:bug: fix(usergroups): handles `NoneType` error in usergroup inspect command

---

riocli/apply/resolver.py

Creation of deployments with native networks were failing with the following error
```
Exception: 'NativeNetwork' object is not subscriptable
```
Native networks and routed networks are returned as class objects by the Rapyuta IO SDK, however the CLI was handling it as a python dictionary. 
This PR resolves the issue by fixing the incorrect syntax.

:bug: fix(deployment): Deployment with native network

---

riocli/organization/__init__.py
riocli/organization/users.py
riocli/organization/utils.py

```
Usage: python -m riocli organization users [OPTIONS]
Lists all users in the organization.
Options:
--help  Show this message and exit.
```
```
→ pipenv run python -m riocli organization users
GUID                                  Name        EmailID                          Status
------------------------------------  ----------  -------------------------------  ---------
fa224b22-9568-4ae7-890f-8c2175bd375b  QA Rapyuta  qa.rapyuta+e2e@gmail.com         ACTIVATED
1f9b5b3f-89a5-4620-bc5c-85de68fab147  aditya jha  aditya.jha@rapyuta-robotics.com  ACTIVATED
e41060bf-f7f2-49e5-ad98-a481328faf40  test test   test.test@rapyuta-robotics.com   ACTIVATED
```

✨ feat(organization): adds command to list users

---

Pipfile
Pipfile.lock
riocli/bootstrap.py
riocli/utils/__init__.py
setup.py

This commit adds a new command to update the CLI to the latest version.
```bash
Usage: rio update [OPTIONS]
Update the CLI to the latest version
Options:
-f, --force, --silent  Skip confirmation
--help                 Show this message and exit.
```
This will make it easier for the users of the CLI to upgrade their local installation with a 
simple command.
```
11:55:26 pallab@pop-os appimages (1) 
→ rio version
rio 0.6.0 / SDK 1.10.0
11:55:34 pallab@pop-os appimages (1) 
→ rio update -f
⚠ Please run this as the root user.
11:55:40 pallab@pop-os appimages (1) 
→ sudo rio update -f
🎉 A newer version (3.1.0) is available.
✔ Update successful!
11:55:48 pallab@pop-os appimages (1) 
→ rio version
rio 3.1.0 / SDK 1.10.0
11:55:56 pallab@pop-os appimages (1)
```
```
→ pipenv run python -m riocli …
```

✨ feat: adds command to update the CLI

---

riocli/apply/__init__.py
riocli/build/model.py
riocli/deployment/model.py
riocli/device/model.py
riocli/disk/model.py
riocli/managedservice/model.py
riocli/model/base.py
riocli/network/model.py
riocli/package/model.py
riocli/project/model.py
riocli/secret/model.py
riocli/static_route/model.py

When we create deployments in rapyuta io, we employ a polling mechanism that polls for the deployment status at regular intervals until the deployment reaches a succeeded or failed state. 
Although the poll count and the interval between successive polls were configurable, however the provision to do so was lacking in the CLI. This PR resolves that by adding two flags `--retry-count` and `--retry-sleep-interval` in the apply command. 
https://github.com/rapyuta-robotics/rapyuta-io-cli/assets/5301901/d192f48c-76da-4cb9-bd11-ec2b8a1b17d7

✨ feat(deployment): adds flags for retry count and sleep interval

---

riocli/deployment/model.py
riocli/deployment/util.py

This PR uses the new SDK changes where poll deployment till ready state is configurable as per deployment phases. 
(https://github.com/rapyuta-robotics/rapyuta-io-sdk/pull/60). Made changes in cli to  poll deployment till provisioning phase. Once the phase of deployment reaches provisioning, it would be available by other deployments to bind.

🚀 perf(deployment): polls deployment till provisioning phase

---

riocli/jsonschema/schemas/usergroup-schema.yaml

The `usergroup` jsonschema had no validation on the group name. This PR fixes that.
```
→ pipenv run python -m riocli apply ~/workspace/playground/riocli-manifests/usergroup.yaml --dryrun
----- Files Processed ----
/home/pallab/workspace/playground/riocli-manifests/usergroup.yaml
Resource Context
--------------------  ------------------
Expected Time (mins)         0.08
Files                         1
Resources                     1
Resource      Action     Expected Time (mins)
------------  --------  ----------------------
usergroup:aa  CREATE             0.08
⠋ Applying... (0:00:00.00)[Err] Object "usergroup:aa" apply failed. Apply will not progress further.
✘ Apply failed. Error: 'aa' does not match '^[a-zA-Z][a-z A-Z0-9-_]{2,61}$'
Failed validating 'pattern' in …
```

🐛 fix(jsonschema): adds regex pattern to usergroup schema

---

.github/workflows/python-compatibility.yml
riocli/utils/__init__.py
setup.py

This PR adds a workflow to check the compatibility of the CLI code against supported Python versions.

👷🏼 ci: adds workflow to check Python version compatibility

---

riocli/deployment/execute.py
riocli/device/vpn.py
riocli/network/delete.py
riocli/parameter/apply.py
riocli/parameter/delete.py
riocli/parameter/upload.py
riocli/utils/spinner.py

The CLI integration tests execute the CLI commands via script that does not have a TTY stream. Yaspin isn't really pipesafe https://github.com/pavdmyt/yaspin/issues/31 and it scrambles the output received in the script.
This PR implements a dummy spinner class that replaces the yaspin spinner when the stream is not a TTY.
[![asciicast](https://asciinema.org/a/600665.svg)](https://asciinema.org/a/600665)
**Runs `rio secret delete` via script**
```
09:56:20 (rapyuta-io-cli-eJqwJnu2) pallab@pop-os rapyuta-io-cli ±|fix/disable-spinner-if-notty ✗|
→ python test.py 
✅ Secret deleted successfully.
```
**Runs `rio apply` via script**
```
09:59:02 (rapyuta-io-cli-eJqwJnu2) pallab@pop-os rapyuta-io-cli ±|fix/disable-spinner-if-notty ✗|
→ python test.py 
----- Files Processed ---- …
```

🐛 fix: implements dummy spinner for non-tty environments

---

riocli/device/delete.py

This PR fixes the error handling in the `rio device delete` command.
**Before**
```
→ rio device delete test-devices-99
Deleting device test-devices-99 (241d4aa7-acd1-4083-86cb-7ce8756150b6) [y/N]: y
✅ Device deleted successfully
```
**After**
```
→ rio device delete test-devices-99 -f
❌ Failed to delete device: Device has running deployments. Please de-provision them before deleting the device.
```

🐛 fix(device): fixes error handling when deleting a device

---

riocli/apply/parse.py

This PR fixes the apply command to return an exit code when it fails.
> Wrike: https://www.wrike.com/open.htm?id=1175574159

🐛 fix(apply): returns exit code when apply command fails

---

riocli/apply/util.py

The apply command does not read nested directories well and hence, it is not possible to break down manifests into sub-directories and apply them by just passing the root directory as the input along with values and secrets. The traversal does happen while the files are processed, however, the final list of files ends up with directories that cannot be processed during the `apply` phase.
This commit filters out all the files and returns them omitting any directories.
> Wrike: https://www.wrike.com/open.htm?id=1174458355

🐛 fix(apply): reads files within nested directories

---

riocli/apply/parse.py
riocli/apply/util.py
riocli/device/delete.py

🎉 release: v4.0.2

---

riocli/bootstrap.py
riocli/utils/__init__.py

This PR fixes the following issues with the `rio update` command
- requires privileged access to update the appimage even when the file is at a non-privileged location
- The file move fails with the error: `Invalid cross-device link: '/tmp/tmp354y0nsn/rio' -> '/home/ankit/.local/bin/rio'`
```
01:43:02 pallab@pop-os appimages 
→ rio version
rio 0.6.0 / SDK 1.11.1
01:43:06 pallab@pop-os appimages 
→ rio update -f
🎉 A newer version (4.0.3) is available.
⚠️ Please consider running as a root user.
❌ Failed to update: [Errno 13] Permission denied: '/usr/local/bin/rio'
01:43:13 pallab@pop-os appimages 
→ doas rio update -f
🎉 A newer version (4.0.3) is available.
✅ Update successful!
01:43:26 pallab@pop-os appimages 
→ doas cp rio /usr/local/bin/
01:43:42 pallab@pop-os appimages 
→ sudo rio …
```

🐛 fix(update): removes the requirement of privileged access

---

.github/workflows/python-compatibility.yml
riocli/apply/manifests/package-nonros-device.yaml
riocli/apply/manifests/package-ros-device-no-rosbag.yaml
riocli/apply/manifests/package-ros-device-rosbag.yaml
riocli/apply/manifests/package.yaml
riocli/jsonschema/schemas/package-schema.yaml
riocli/package/model.py

This commit adds support for defining liveness probe. You can set HTTP, EXEC or TCP liveness probe
Demo: https://asciinema.org/a/X6Z2IgL0XXHvSbM5rcvBtPIk1
Manifest: https://drive.google.com/file/d/19KmQ6npDzAm6LGlDkK-DxcfXnddVfwRE/view?usp=sharing

✨ feat(deployment): exposes healthcheck probes for device deployments

---

riocli/apply/manifests/package-nonros-device.yaml
riocli/apply/manifests/package-ros-device-no-rosbag.yaml
riocli/apply/manifests/package-ros-device-rosbag.yaml
riocli/apply/manifests/package.yaml
riocli/jsonschema/schemas/package-schema.yaml

The `httpGet` section of `livenessProbe` has a mistake that leads to an incorrect payload which lead of deployment failures.

fix(jsonschema): corrects property name in package livenessProbe definition

---

riocli/usergroup/inspect.py

The inspect output did not conform with the JSONSchema and using it as is was not possible. This commit corrects the output and the output will now be usable with the rio apply command.

🐛 fix(usergroup): corrects the inspect output

---

riocli/apply/resolver.py
riocli/deployment/model.py
riocli/static_route/model.py

The `find_functor` for staticroute was not able to parse URLs of the kind `ims-coredev-axylr.ep-r.io`. The easier way is to simply parse the name instead and split on the first `-` from the right.
```yaml
---
kind: "StaticRoute"
metadata:
name: "testnginx"
labels:
app: nginx
---
kind: Package
metadata:
name: "nginx"
version: "1.0.0"
labels:
app: nginx
spec:
runtime: cloud
cloud:
replicas: 1
executables:
- name: nginx
type: docker
docker:
image: nginx
endpoints:
- name: "testnginx"
type: external-http
port: 80
targetPort: 80
---
kind: Deployment
metadata:
name: "nginx-dep"
depends:
kind: package
nameOrGUID: "nginx"
version: "1.0.0"
spec:
runtime: cloud
staticRoutes: …
```

🐛 fix: fixes static route dependencies during apply

---

riocli/apply/resolver.py
riocli/deployment/model.py
riocli/static_route/model.py

This release contains fixes related to static routes.

🎉 release: v4.1.1

---

riocli/vpn/status.py

This PR fixes the `rio vpn status` command to show the DNS name of nodes instead of the host name registered with headscale. The DNS name is the one that is resolved by MagicDNS and not the host name and thus, it seems more intuitive to show the DNS name. The host name can be inferred from this name as well.
```
→ pipenv run python -m riocli vpn status
ℹ️ VPN is enabled in the project (lgs-hmr-001)
IP           DNS Name                                               OS     Online    Active
-----------  -----------------------------------------------------  -----  --------  --------
100.64.0.12  edge01-kyjqi1iz                                        linux  True      False
100.64.0.1   subnet-router.rapyuta.rio.internal                     linux  True      False
100.64.0.14 …
```

🐛 fix(vpn): displays DNS name in vpn status

---

Pipfile
Pipfile.lock
riocli/organization/__init__.py
riocli/organization/invite_user.py
riocli/organization/remove_user.py
riocli/organization/users.py
riocli/organization/utils.py
setup.py

This PR introduces two new sub-commands under `rio organization` to invite and remove a user from the current organization.
```
Usage: rio organization [OPTIONS] COMMAND [ARGS]...
Organizations in rapyuta.io
Options:
--help  Show this message and exit.
Commands:
invite-user  Invite a new user to the current organization
list         List all the organizations that you are a part of
remove-user  Remove a user from the current organization
select       Sets the current organization to the one provided in the...
users        Lists all users in the organization.
```

✨ feat(organization): user management in organization

---

riocli/usergroup/inspect.py

There are cases when a project is deleted before being removed from the group. Since this is use case that we allow, in the recent v2 API changes, the delete project does not update the association tables. Hence, the `GET /api/groups/:id` call ends up getting the projects in the DB. But they don't have any role associated with them which breaks the inspect command.
This PR fixes that by handling such projects that do not have a corresponding role. However, the right way to do things would be to update the association tables corresponding a project.

fix(usergroup): fixes inspect when group has deleted projects

---

riocli/vpn/connect.py
riocli/vpn/util.py

A few `tailscale` commands require root privilege to run and are executed with `sudo`. However, when the user is already the root user, the CLI throws an error. This PR fixes that by adding sudo only when the executing user is non-root.

🐛 fix(vpn): avoids sudo when running as root

---

riocli/device/delete.py
riocli/device/util.py

This commit updates device delete command that enables users to conveniently delete existing devices by providing device name or regex that can delete multiple devices
```
Usage: rio device delete [OPTIONS] [DEVICE_NAME_OR_REGEX]
Deletes one more devices
Options:
-f, --force, --silent  Skip confirmation
-a, --delete-all       Deletes all devices
-w, --workers INTEGER  number of parallel workers while running delete device command. defaults to 10.
--help                 Show this message and exit.
```
[![asciicast](https://asciinema.org/a/601159.svg)](https://asciinema.org/a/601159)

✨ feat(device): updates device delete command to delete multiple devices

---

riocli/project/features/vpn.py

The command to enable vpn on the project now also supports subnets.
```
rio project feature vpn dev-tst-001 true --subnets 10.81.0.0/16
```
```
Usage: rio project features vpn [OPTIONS] PROJECT_NAME
ENABLE
Enable or disable VPN on a project
Example:
rio project features vpn "my-project" true
rio project features vpn "my-project" true --subnets 10.81.0.0/16
Options:
--subnets TEXT  Subnet ranges for the project. For example: 10.81.0.0/16
--help          Show this message and exit.
```

feat(project): accepts subnets while enabling vpn

---

riocli/apply/resolver.py
riocli/device/delete.py
riocli/jsonschema/schemas/deployment-schema.yaml
riocli/jsonschema/schemas/secret-schema.yaml
riocli/organization/select.py

Test manifests:
adds validation for applying cloud disk on device deployment
```
---
apiVersion: apiextensions.rapyuta.io/v1
kind: Package
metadata:
description: Sootballs Printer Cups package
labels:
app: printer_cups
name: sootballs_printer_cups
version: 2.0.1-kokubu
spec:
device:
arch: amd64
restart: always
executables:
- docker:
image: nginx
name: cups
runAsBash: false
type: docker
runtime: device
#---
apiVersion: apiextensions.rapyuta.io/v1
kind: Deployment
metadata:
depends:
kind: package
nameOrGUID: pkg-oytmqdbzeajwyxsgczeawfzd
version: 2.0.1-kokubu
labels:
app: printer_cups
name: sootballs_printer_cups
spec:
device:
depends:
kind: device
nameOrGUID: romil-v3
runtime: device
volumes:
- execName: cups
mountPath: /etc/cups/printers.conf
subPath: …
```

🐛 fix: miscellaneous bug fixes

---

riocli/deployment/model.py
riocli/jsonschema/schemas/deployment-schema.yaml
riocli/jsonschema/validate.py
riocli/parameter/apply.py
riocli/parameter/list.py
riocli/parameter/utils.py

This commit sets additionalProperties = false in case of the runtime dependency in deployments that allowed including unlisted attributes in the manifest. For example, including staticRoutes for device deployments is valid without the fix.
Environment: io-dev
Organization: Rapyuta
Project: biswa
The following manifest is invalid and the apply command should throw and error.
```yaml
kind: Package
metadata:
name: "postgres"
version: "1.0.0"
labels:
app: postgres
spec:
runtime: device
device:
arch: amd64
restart: always
executables:
- name: postgres
type: docker
docker:
image: postgres:15.2
environmentVars:
- name: "POSTGRES_PASSWORD"
default: "postgres"
---
kind: Deployment
metadata:
name: …
```

fix(jsonschema): disallows additional properties for runtimes dependency

---

riocli/disk/model.py
riocli/jsonschema/schemas/disk-schema.yaml
riocli/jsonschema/validate.py

The runtime field hasn't been a mandatory field in the disks jsonschema. This commit corrects that by making them mandatory and it removes the default making the requirement an explicit one.

 fix(jsonschema): makes runtime required in disks

---

riocli/deployment/delete.py
riocli/device/delete.py
riocli/package/delete.py

This PR corrects the commands that do not return a non-zero exit code when a resource is not found during delete. The commands are
- `rio device delete`
- `rio package delete`
- `rio deployment delete`

🐛 fix: miscellaneous bugs

---

riocli/disk/model.py

This fix introduces a retry mechanism for disk deletion operations, ensuring that deletion attempts are retried in the event of errors, regardless of the current disk status.

fix(disk): implements retry mechanism for disk deletion

---

riocli/apply/resolver.py
riocli/deployment/logs.py
riocli/disk/util.py
riocli/organization/utils.py
riocli/parameter/utils.py
riocli/utils/execute.py

Fixes the issue where the `.apps.rapyuta.io` routes were used as default in some API calls that started failing after migrating to AKS. This PR fixes the issue by updating the default routes.

fix: updates default service urls in api calls

---

riocli/jsonschema/schemas/deployment-schema.yaml

The depends attribute of the deployment schema is defined under the componentSpec which violates the additionalProperties=False setting of the dependencies for each runtime. This commit correct that by explicitly adding the depends section for each runtime.
_**The spec.**_
```yaml
spec:
runtime: device
device:
depends:
kind: device
nameOrGUID: "{{ device.edge.name }}"
depends:
- kind: deployment
nameOrGUID: oks_server
```
**_The error._**
```
>> :white_tick: Updated deployment:oks_web_interface                                                                                                [2024-02-01T12:23:19.016449]
:x: Apply failed. Error: {'runtime': 'device', 'device': {'depends': {'kind': 'device', 'nameOrGUID': 'edge01', 'guid': '3d6e8b0f-d3f1-4750-898e-253eb08e414e'}}, 'depends': …
```

fix(jsonschema): corrects deployment component spec

---

riocli/deployment/util.py
riocli/device/util.py
riocli/package/util.py

This PR fixes the logic to fetch packages, devices and deployments based on a name, uuid and pattern. Release v7.0.0 has a bug that assumes all names to be patterns. For example, look at the following output
```
→ rio device list
Device ID                             Name          Status
------------------------------------  ------------  ----------
e93aaabf-0521-421a-bbb6-7249321e91c5  amit-testing  ONLINE
496c6c55-094f-4284-be01-5d9ca283d1c7  biswa1        ONLINE
005e3b19-929b-40ec-9230-6c624fc342c6  pallab        REGISTERED
f62a18a8-27c6-4b30-8463-93fb089a412d  pallab01      REGISTERED
6bddf8ff-dd85-4236-94e1-ee84fdc8959c  pallab011     REGISTERED
→ rio device delete pallab
Name       Device ID                             Status
---------  ------------------------------------ …
```

🐛 fix: corrects the condition to fetch various resources

---

riocli/apply/parse.py

When a resource manifest has no name in metadata, it throws a KeyError. This commit fixes the error reporting to state the issue more explicitly.

🐛 fix(apply): raises error when a metadata has no name

---

riocli/jsonschema/schemas/deployment-schema.yaml

The regex for device volume mount and subpath does not account for files and only accepts directories. However, this is not the expectation as we can mount either files or directories. This commit corrects the regex.
Referring a regex found here: https://regex101.com/r/wal8VG/33
Wrike Ticket: https://www.wrike.com/open.htm?id=1295041413
```yaml
apiVersion: apiextensions.rapyuta.io/v1
kind: Deployment
metadata:
name: gateway
depends:
kind: package
nameOrGUID: gateway
version: "1.0.0"
spec:
runtime: device
device:
depends:
kind: device
nameOrGUID: "{{ device.edge.name }}"
volumes:
- execName: "gateway"
mountPath: "/etc/caddy/config.json"
subPath: "/opt/rapyuta/configs/gateway/config.json"
- execName: "gateway"
mountPath: "/etc/caddy/Caddyfile"
subPath: …
```

fix(jsonschema): corrects the regex for device volume paths

---

riocli/v2client/client.py

The existing limits for list secrets and static routes were set to 10 which is quite low. This leads to an increased number of calls to the apiserver. This commit increases the limit to 50, reducing the calls required to fetch all the items.

fix(v2client): updates limits for list secrets and routes

---

riocli/deployment/delete.py
riocli/deployment/update.py
riocli/device/delete.py

Certain confirmations had the default action set to True. This would mean that if someone hits the return key, then it will go ahead and perform the action. It may lead to unwanted consequences and thus a risky option to have in the CLI. This commit fixes that.
Wrike Ticket: https://www.wrike.com/open.htm?id=1299312443

fix: sets default confirmation action to 'No'

---

riocli/deployment/delete.py
riocli/deployment/update.py
riocli/deployment/util.py
riocli/device/delete.py
riocli/device/util.py
riocli/package/util.py

This PR resolves the following tickets:
* https://www.wrike.com/open.htm?id=1300147027
* https://www.wrike.com/open.htm?id=1300152105
* https://www.wrike.com/open.htm?id=1300152784
* https://www.wrike.com/open.htm?id=1299310557
* https://www.wrike.com/open.htm?id=1299312443
**Reported By:** @biswakalyansahoo 
```
→ pipenv run python -m riocli device list
Device ID                             Name                  Status
------------------------------------  --------------------  ----------
1007d68b-7912-43da-8091-fd947bc52da8  amr01                 REGISTERED
3736bc21-84ea-4a7d-82ad-8acc5a2b2151  amr01_robotui         REGISTERED
23f20e03-bfd3-4746-9a92-ddbb82c64972  etcd_amr01            REGISTERED
51b0dc70-27bd-47c2-b640-ed8f50b7881e  otel-collector-amr01  REGISTERED
→ pipenv run python …
```

🐛 fix: resolves issues around regex based ops

---

riocli/config/config.py
riocli/project/__init__.py
riocli/project/util.py
riocli/project/whoami.py
riocli/v2client/client.py

This commit introduces a new command that will help determine if a user has admin access in a certain project. It will print 'Yes' if the current context's user has 'admin' role in a given project. Else, it will print 'No'.
Wrike Ticket: https://www.wrike.com/open.htm?id=1291068805
```
→ pipenv run python -m riocli project --help
Usage: python -m riocli project [OPTIONS] COMMAND [ARGS]...
High-level groups for other resources
Options:
--help  Show this message and exit.
Commands:
create    Creates a new project
delete    Deletes a project
features  Toggle features on a project
inspect   Inspect the project resource
list      List all the projects you are part of
select    Sets the given project in the CLI context.
whoami    What is the role of the current user in the PROJECT?
→ pipenv run …
```

feat(project): implements whoami command

---

riocli/project/__init__.py
riocli/project/list.py

This commit fixes a regression from a previous commit where we have removed the implicit population of organization_guid from the context in the v2Client. As consquence, the list project was fetching the entire list of projects.

fix(projects): fixes the list command

---

riocli/project/util.py

The `find_project_guid` expects an organization guid. However, the `name_to_guid` decorator that calls the helper function did not send it. It led to cases where you can resolve guids of projects not present in the organization of the current context.

fix(project): sends org when fetching guid from name

---

riocli/auth/login.py
riocli/auth/util.py

This commit fixes the issue where `email_id` of the user is not saved when rio auth login --auth-token TOKEN is invoked.
Wrike Ticket: https://www.wrike.com/open.htm?id=1329601684
```
→ rm -f ~/.config/rio-cli/config.json 
→ pipenv run python -m riocli auth login --auth-token X5PdoCZs9O0bAPbohdXiQVt32RUe2N6E81j1foT0 --project sga-sak-002 --organization warehouse --silent
ℹ️ Token belongs to user itaru.fujiwara@rapyuta-robotics.com
Your project has been set to 'sga-sak-002' in the organization 'warehouse'
✅ Logged in successfully!
→ pipenv run python -m riocli project whoami
admin
```

fix(auth): saves email_id when logged in with auth_token

---

riocli/project/whoami.py

fix(project): corrects usergroup role check in whoami command

---

riocli/apply/resolver.py
riocli/secret/model.py

Due to a recent refactor in the v2 client library,
the list secrets function now returns the entire
secret objects instead of just reading the metadata
in the previous implementation. This changed object
altogther and the way other sections of code fetched
the secret name.
This commit addresses the issue by correcting the
find functions and other methods where secret name is
referred to.

fix(secret): corrects the corresponding find functor

---

riocli/configtree/import_keys.py
riocli/configtree/revision.py
riocli/configtree/tree.py

The initial implementation of the configtree provided an option to
operate on project-scoped trees using the --project flag. However, after
considering the use cases, we have come to an understanding that it is
more common to operate on project-scoped trees than the
organization-scoped trees. Hence, this commit replaces the --project
with --organization flag. Specifying the flag means that the user wants
to operate on the organization-scoped config trees only.
```
→ rio configtree list --help
Usage: rio configtree list [OPTIONS]
Lists the Config trees.
Options:
--organization  Operate on organization-scoped Config Trees only.
--help          Show this message and exit.
```

fix(configtree): replace --project with --organization flag

---

riocli/v2client/client.py
riocli/vpn/__init__.py
riocli/vpn/connect.py
riocli/vpn/machines.py
riocli/vpn/util.py

This PR introduces a subcommand to manage Android and iOS devices on rapyuta.io VPN. Run the following command to know more.
```
rio vpn machines --help
```

feat(vpn): add support for registering machine for Android or iOS

---

riocli/vpn/util.py

This commit fixes the expiry time format while generating a managed service binding in the `rio vpn connect` command.

fix(vpn): fix the expiry time formatting for vpn binding

---

riocli/configtree/import_keys.py
riocli/configtree/revision.py
riocli/configtree/tree.py

The Revision context manager stores the latest revision in the Statefile to
avoid typing revision explicitly every time. However the recent change to make
the Project the default context caused some mishandling for Org-level trees.
This caused all the keys to be stored with ProjectGUID as the top-level.
The fix is to not provide the =project_guid= parameter to Statefile helper
functions in case of Org-level tree.

fix(configtree):  fix handling org-level tree revisions in statefile 

---

riocli/secret/list.py

Due to a recent refactor in the v2 client library, the list secrets function now returns the entire
secret objects instead of just reading the metadata in the previous implementation. This changed object altogther and the way other sections of code fetched the secret name.
This commit addresses the issue by correcting the
list_secrets function.

fix(secret): corrects list secret command

---

setup.py

The setup.py file doesn't specify the minimum Python version requirement. This leads to installation on unsupported Python versions. We had dropped support for Python 3.7 and lower months ago, however it is still possible to install it on system with lower Python versions.

chore: updates python_requires in setup.py

---

riocli/apply/resolver.py

While fixing a regression, the guid  functor for secret was updated to return a name. This led to a regression in the apply command where secrets created along with other packages weren't being resolved correctly. This commit fixes that.
Used the following test manifest:
```yaml
---
apiVersion: apiextensions.rapyuta.io/v1
kind: Secret
metadata:
name: test-secret
spec:
type: Docker
docker:
registry: quay.io/rapyuta
username: "quayuser"
password: "quaypass"
email: rr@rr.com
---
kind: Package
metadata:
name: "nginx"
version: "1.0.0"
labels:
app: nginx
spec:
runtime: cloud
cloud:
replicas: 1
executables:
- name: nginx
type: docker
docker:
image: nginx
pullSecret:
depends:
kind: secret
nameOrGUID: "test-secret"
```

🐛 fix(apply): fixes the secret guid functor in the resolver

---

Pipfile
Pipfile.lock
docs/source/hwil.rst
docs/source/index.rst
riocli/bootstrap.py
riocli/config/__init__.py
riocli/config/config.py
riocli/exceptions/__init__.py
riocli/hwil/__init__.py
riocli/hwil/create.py
riocli/hwil/delete.py
riocli/hwil/execute.py
riocli/hwil/inspect.py
riocli/hwil/list.py
riocli/hwil/login.py
riocli/hwil/ssh.py
riocli/hwil/util.py
riocli/hwilclient/__init__.py
riocli/hwilclient/client.py
riocli/utils/__init__.py
riocli/utils/ssh_shell.py
setup.py

This pull request introduces the `hwil` command to manage hardware-in-loop devices.
```
Usage: rio hwil [OPTIONS] COMMAND [ARGS]...
Manage Hardware-in-the-Loop (HWIL) devices
Options:
--help  Show this message and exit.
Commands:
create   Create a new hardware-in-the-loop device.
delete   Delete one or more devices
execute  Execute
inspect  Inspect the hardware-in-the-loop device.
list     Lists hardware-in-loop devices.
login    Log in to HWIL.
ssh      SSH into the hardware-in-the-loop device.
```
[![asciicast](https://asciinema.org/a/663724.svg)](https://asciinema.org/a/663724)
[![asciicast](https://asciinema.org/a/663820.svg)](https://asciinema.org/a/663820)

feat(hwil): implements hwil command

---

riocli/device/util.py

The highperf label is not being set when set to True in the manifest. This commit fixes the issue.
```yaml
kind: "Device"
metadata:
name: "test01"
labels:
purpose: testing
app: test
spec:
python: "3"
rosDistro: "melodic"
virtual:
enabled: True
product: "sootballs"
arch: "amd64"
os: "ubuntu"
codename: "focal"
highperf: true
docker:
enabled: True # Required
rosbagMountPath: "/opt/rapyuta/volumes/rosbag"
```

fix(device): sets highperf label on virtual device

---

riocli/project/features/vpn.py

The rio project features vpn command does not update the subnet if the VPN is already enabled. The reason is a check that returns if the current state is already the desired one.
This commit removes the check and allows an update to happen irrespective and thus allowing the subnet range updates to work.
Wrike Ticket: https://www.wrike.com/open.htm?id=1418307735
> Slack Thread: https://rapyuta-robotics.slack.com/archives/CBAP39MGD/p1719467131181389?thread_ts=1719465795.794819&cid=CBAP39MGD

fix(project): updates subnet when vpn is already enabled

---

riocli/v2client/client.py

This PR updates the v2 client to set the organization guid header for all API calls.
Slack Reference: https://rapyuta-robotics.slack.com/archives/C04F6FHF4BS/p1719994868878939

fix(v2client): set organizationguid header by default

---

riocli/apply/util.py

The output of the rio template command is currently
not sorted by file name. This makes it slightly
inconvenient to read through the rendered templates.
In this commit, we sort the files before rendering them.

feat(template): sort rendered template by file name

---

riocli/apply/manifests/device.yaml
riocli/jsonschema/schemas/device-schema.yaml

Users can now set platform as a product type when they create virtual devices using device manifests.
Wrike Ticket: https://www.wrike.com/open.htm?id=1460556021

fix(jsonschema): add platform as a product for virtual devices

---

riocli/configtree/etcd.py

This pull request addresses a request made by @tetorea that the keys imported in etcd via the CLI do not have a leading `/` and that the applications relying on the feature expect the `/` in the keys that they are reading.
To solve the issue, we are adding a `/` when a prefix is not specified when importing the keys into etcd.
```
→ etcdctl get --prefix --keys-only /
/master/apis/gwm_auth_token
/master/apis/gwm_core_url
```

fix(configtree): prefix keys with '/' when importing to etcd

---

riocli/configtree/etcd.py

This PR adds the logic to update the sentinel key when config is imported into etcd.
Wrike Task: https://www.wrike.com/open.htm?id=1459385386

fix(configtree): update sentinel key when tree is imported in etcd

---

riocli/organization/select.py

The organization select command checks whether the currently set organization is already the selected one. It relies on the organization_id in the config. However, there may be a case where the config may not have the organization entry. In such a case, accessing the key without .get() throws a key error. This commit rectifies the issue.
Wrike Ticket:

fix(organization): fix organization select command

---

riocli/configtree/etcd.py
riocli/configtree/export_keys.py
riocli/configtree/import_keys.py

This commit adds the support for config overrides while importing configurations from files. Users can specify one or more override files and they will be applied to the base configs in order. It is expected that the overrides have the full key hierarchy such that the command is able to match the right override with the base config.
Additionally, this PR exposes the CLI option to export trees in YAML or JSON format.
Wrike Ticket: https://www.wrike.com/open.htm?id=1459374448
```
Usage: rio configtree import [OPTIONS] TREE_NAME
[FILES]...
Imports keys from JSON or YAML files.
The import command can import keys into an existing Config Tree or to an
ETCD cluster. It can also output the keys to files in JSON or YAML format.
The command can also apply overrides to the keys before importing …
```

feat(configtree): supports overrides while importing config from files

---

.github/workflows/gh-pages.yml
scripts/install.sh

This commit introduces a script to download an install appimages. This will provide convenience to the users of the CLI who want to download and use the appimage.
```
→ ./install.sh v8.1.0
⏳ Downloading release v8.1.0...
############################################################################################################################################################################################################################################### 100.0%
✅ Installation complete! You can now run 'rio auth login' to get started.
```

feat(scripts): adds install script for appimages

---

scripts/install.sh

This PR updates the script to simply print this.
```
→ cat ./scripts/install.sh | bash
_          _       
_ __ __ _ _ __  _   _ _   _| |_ __ _  (_) ___  
| '__/ _` | '_ \| | | | | | | __/ _` | | |/ _ \ 
| | | (_| | |_) | |_| | |_| | || (_| |_| | (_) |
|_|  \__,_| .__/ \__, |\__,_|\__\__,_(_)_|\___/ 
|_|    |___/                          
⏳ Downloading the latest release...
######################################################################## 100.0%
✅ Installation complete! You can now run 'rio auth login' to get started.
```

🔧 chore: adds rapyuta.io trademark banner

---

.github/workflows/python-compatibility.yml
Pipfile
Pipfile.lock
riocli/auth/login.py
riocli/organization/select.py
riocli/project/select.py
riocli/vpn/connect.py
riocli/vpn/disconnect.py
riocli/vpn/util.py
setup.py

Since our headscale runs without `magicDNS` enabled, it is impossible to resolve VPN peers using their DNS names. `magicDNS` cannot be enabled since we have faced multiple DNS resolution-related issues in the past that break the VPN connectivity in warehouses.
However, VPN users in Flaptter have requested the ability to access devices and services running on them via hostnames. 
To fulfill the requirement, this PR populates the hosts file on a user's system with the devices on rapyuta.io that have VPN enabled. Thus, it is possible to access any device via its hostname when connected over VPN.
To use the feature, users will have to run the following command
```
rio vpn connect --update-hosts
```
https://github.com/user-attachments/assets/26cd6d08-f9cc-4ce8-8fff-cac12f22078e

feat(vpn): adds option to populate vpn peers in hosts file

---

riocli/apply/__init__.py
riocli/apply/manifests/device.yaml
riocli/apply/parse.py
riocli/apply/template.py
riocli/apply/util.py
riocli/chart/apply.py
riocli/chart/delete.py
riocli/device/model.py
riocli/device/util.py
riocli/jsonschema/schemas/device-schema.yaml
riocli/package/delete.py
riocli/secret/delete.py
riocli/secret/util.py
riocli/static_route/delete.py
riocli/static_route/util.py

This pull request addresses multiple requests. Please check the commits for more details.

✨ feat: miscellanous improvements

---

riocli/device/report.py

The device report command should only work for online devices. This commit adds the check to ensure that.
```
02:46:32 (.venv) pallab@pop-os rapyuta-io-cli ±|fix/do-not-report-registered-device|
→ uv run rio device report registered
⚠️ Device is not online. Skipping report.
```

fix(device): report online devices only

---

pyproject.toml
riocli/apply/filters.py
uv.lock

This PR implements the `get_intf_ip` template filter that will help fetch the IP of a device interface. Here's an example
```yaml
envArgs:
- name: EDGE_VPN_IP
value: {{ 'edge01' | get_intf_ip(interface='tailscale0') }}
```
Note: This will introduce a slight delay in applying the template.
* https://github.com/rapyuta-robotics/rapyuta-io-sdk/pull/84

feat(apply): adds template func to get interface ip

---

riocli/organization/list.py

When we login with auth token in silent mode, there's no org selected. The config has no org present either. This breaks the list command that tries to fetch the selected org from config to highlight it in the output.
```
03:26:43 pallab@pop-os rr_flaptter_deploy ±|devel ✗|
→ rio organization list
'organization_id'
03:26:51 pallab@pop-os rr_flaptter_deploy ±|devel ✗|
→ cat ~/.config/rio-cli/config.json 
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ File: /home/pallab/.config/rio-cli/config.json
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────── …
```

fix(organization): fixes key error when no org is selected

---

riocli/apply/manifests/device.yaml
riocli/device/util.py
riocli/hwil/create.py
riocli/jsonschema/schemas/device-schema.yaml

Introduces support for specifying device expiry in the manifest as well as the `rio hwil` command.

feat: adds option for virtual device expiry

---

riocli/config/config.py

Overrides the CLI config filepath with the RIO_CONFIG env variable if set.
Use case
Automating parallel deployments with the RIO CLI as done in
https://github.com/rapyuta-robotics/rr_lsd_staging
deploy.py 
Usage like
RIO_CONFIG=./path/to/config.json rio project list

feat: add RIO_CONFIG env override

---

pyproject.toml
riocli/apply/__init__.py
riocli/apply/util.py
uv.lock

Resolves [AB#39151](https://dev.azure.com/rapyuta-robotics/3151e969-9eb7-4729-b4e8-8c659c416104/_workitems/edit/39151)

feat(apply): add support for ansible filters in Jinja2

---

riocli/apply/manifests/device.yaml
riocli/device/model.py
riocli/device/util.py
riocli/hwilclient/client.py
riocli/jsonschema/schemas/device-schema.yaml
uv.lock

This pull request includes the following set of changes
* ✨ Adds project id to the `hwil` device name when a virtual device is created using a device manifest.
* 🐛 When a hwil device goes into a failed state while applying a device manifest and the rio device isn't created, the `rio delete` operation fails to clean it up since it returns when the rio device is not found. This pull request fixes that by attempting to clean-up if a corresponding hwil device exists.
* 🐛 Let's say a previous apply led to the hwil device going into the failed state, re-applying the manifest doesn't clean-up the device and returns the details of the existing failed device. This renders the re-apply useless. This pull request fixes that by cleaning up the failed hwil device and re-creating it.
Resolves …

feat(device): handles failed hwil devices during apply and delete

---

riocli/apply/manifests/deployment-nonros-device.yaml
riocli/apply/manifests/deployment.yaml
riocli/jsonschema/schemas/deployment-schema.yaml

Resolves [AB#33922](https://dev.azure.com/rapyuta-robotics/3151e969-9eb7-4729-b4e8-8c659c416104/_workitems/edit/33922)

feat(deployment): adds an option to block paramsync until ready

---

riocli/device/report.py

This pull request includes a small change to the `riocli/device/report.py` file. The change removes the `hidden=True` attribute from the command configuration to make the command visible in the help output.

🔧 Chore: Report device command visible

---

riocli/apply/manifests/package.yaml
riocli/jsonschema/schemas/package-schema.yaml

This PR modifies the host pid namespace item and this prop uses for schema validation.

feat(package): supports hostPID for package

---

riocli/apply/filters.py
riocli/apply/util.py
riocli/device/util.py

The `get_intf_ip` filter now supports a comma-separated list of network interfaces. It returns the first IP address found among the specified interfaces.
Additionally, the filter is optimized to cache results, preventing repeated network calls and ensuring better performance when used multiple times in a workflow.

feat(apply): add support for multiple interfaces in get_intf_ip filter

---

riocli/deployment/delete.py
riocli/device/delete.py
riocli/disk/delete.py
riocli/network/delete.py
riocli/package/delete.py
riocli/secret/delete.py
riocli/static_route/delete.py

Issue: The CLI returns exit code 1 when resources are not found for --all or no regex or name match.
This PR fixes the issues by returning exit code 0 if resource not found i.e no resource to delete

fix(cli): returns success in case deployment, package, secret, route, device, disk, network not found while deleting

---

riocli/apply/manifests/project.yaml
riocli/device/inspect.py
riocli/jsonschema/schemas/project-schema.yaml
riocli/project/features/__init__.py
riocli/project/features/dockercache.py
riocli/project/model.py
riocli/v2client/client.py
riocli/vpn/util.py

Resolves [AB#43805](https://dev.azure.com/rapyuta-robotics/3151e969-9eb7-4729-b4e8-8c659c416104/_workitems/edit/43805)
Resolves [AB#47896](https://dev.azure.com/rapyuta-robotics/3151e969-9eb7-4729-b4e8-8c659c416104/_workitems/edit/47896)

:sparkles: feat(project): add support for docker-cache feature

---

riocli/device/vpn.py

This pull request includes changes to the `riocli/device/vpn.py` file to improve the handling of VPN devices by including both online and offline devices in the process. The most important changes include modifying the `toggle_vpn` function to use a new helper function and adding the helper function to retrieve both online and offline devices.
Resolved [AB#50651](https://dev.azure.com/rapyuta-robotics/3151e969-9eb7-4729-b4e8-8c659c416104/_workitems/edit/50651)

feat: enable/disable vpn in offline devices.

---

pyproject.toml
riocli/device/execute.py
uv.lock

With `--async`
```
╭─ ~/Projects/python/rapyuta-robotics/rapyuta-io-cli on feat/exec-on-multiple-devices !2                     took 17s Py rapyuta-io-cli at 13:17:09
╰─❯ uv run rio device execute '.*' 'uname -a' --async
>>> 17098c40-5aec-42a7-bd4d-825bc72f4699: Success
Linux controller2 5.15.0-86-generic #96~20.04.1-Ubuntu SMP Thu Sep 21 13:23:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
>>> f1677d7d-07c7-4877-905b-ef4dfe56426a: Success
Linux nuc-sn-btws24200glv 6.5.0-1020-oem #21-Ubuntu SMP PREEMPT_DYNAMIC Wed Apr  3 14:54:32 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
>>> e7ac3b0a-bdf1-4c8a-a4aa-f38187831ebd: Success
Linux edge2 6.5.0-1020-oem #21-Ubuntu SMP PREEMPT_DYNAMIC Wed Apr  3 14:54:32 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
Without `--async`
```
╭─ …
```

feat(device): execute command on multiple devices

---

riocli/apply/__init__.py
riocli/apply/filters.py
riocli/apply/parse.py
riocli/apply/template.py
riocli/apply/util.py

Resolves [AB#59533](https://dev.azure.com/rapyuta-robotics/3151e969-9eb7-4729-b4e8-8c659c416104/_workitems/edit/59533)
```
ℹ️ Organization: Rapyuta (org-wvnwcmvfkbajavjetttcutga)
ℹ️ Project: ankit (project-cp3fv3ojkeas73fm3oi0)a
--------------------------------------------------------------------------------------- Files Processed ----------------------------------------------------------------------------------------
/home/ankit/.local/src/work/scratch/docker-cache/project.yaml
--------------------------------------------------------------------------------------- Parsed Resources ---------------------------------------------------------------------------------------
Kind     Name
-------  -------------
Project  green-field-1
Project  green-field-2 …
```

feat(apply): add context in the output for apply-family of commands

---

riocli/project/list.py
riocli/v2client/client.py

This PR , fixes the list and inspect project functionality when no organization selected. So for list project without organization selected it will return all projects from all organization where user belongs to. Same for inspect as well.

fix(project): fixes the list and inspect project functionality when no organization selected

---

riocli/bootstrap.py
riocli/oauth2/__init__.py
riocli/oauth2/create.py
riocli/oauth2/delete.py
riocli/oauth2/inspect.py
riocli/oauth2/list.py
riocli/oauth2/update.py
riocli/oauth2/util.py
riocli/v2client/client.py

Resolves https://github.com/rapyuta-robotics/rapyuta_io/issues/725

feat(oauth2): add oauth2 commands

---

riocli/apply/manifests/project.yaml
riocli/jsonschema/schemas/project-schema.yaml
riocli/project/features/dockercache.py

resolves https://github.com/rapyuta-robotics/rapyuta_io/issues/742

feat(dockercache): add registry blob storage option

---

pyproject.toml
riocli/device/execute.py
uv.lock

Follow these steps to build the CLI AppImage on your local machine:
- Switch to the appropriate branch.
- Install dependencies by running:
```bash
uv sync
```
- Download the required AppImage files.
- Extract them into the `scripts/` directory.
* [appimagetool.tar.gz](https://github.com/user-attachments/files/20198119/appimagetool.tar.gz)
* [python_appimage.tar.gz](https://github.com/user-attachments/files/20198126/python_appimage.tar.gz)
You have two options to continue:
```bash
./scripts/build-rio-appimage.sh
```
- **Comment out lines 1–13**. These lines are intended for the AppImage CI pipeline and fetch the AppImage from MinIO.
```bash
chmod +x scripts/*.AppImage
uv build
cp dist/rapyuta_io_cli-*.whl scripts/
sudo apt-get update
sudo apt-get install fuse libfuse2
cd scripts …
```

fix: run commands on devices in background

---

riocli/config/config.py
riocli/hwil/login.py
riocli/hwilclient/client.py

This commit adds X-Email-ID header to all the HWIL requests. If the `email_id` field is not present, then it will skip the header.
Traefik Logs
```
{
"ClientAddr": "103.163.65.90:38744",
"ClientHost": "103.163.65.90",
"ClientPort": "38744",
"ClientUsername": "-",
"DownstreamContentSize": 23403,
"DownstreamStatus": 200,
"Duration": 566382391,
"OriginContentSize": 23403,
"OriginDuration": 566310691,
"OriginStatus": 200,
"Overhead": 71700,
"RequestAddr": "hwilv3.rapyuta.io",
"RequestContentSize": 0,
"RequestCount": 177433,
"RequestHost": "hwilv3.rapyuta.io",
"RequestMethod": "GET",
"RequestPath": "/device/",
"RequestPort": "-",
"RequestProtocol": "HTTP/1.1",
"RequestScheme": "https",
"RetryAttempts": 0,
"RouterName": "websecure-hwil-hwilv2-hwilv3-rapyuta-io@kubernetes",
"ServiceAddr": …
```

✨ feat(hwil): add X-Email-ID header in HWIL requests

---

riocli/apply/util.py

Ansible added this new filter in v2.19.0 that replaces the Jinja2's built-in default filter. The Ansible's version breaks some manifests.
https://github.com/ansible/ansible/blob/faf86ca2b3e7b06660528d69a9839bb8d1409f70/lib/ansible/plugins/filter/core.py#L669
Resolves rapyuta-robotics/rapyuta_io#997

fix(apply): fix the `default` behaviour in the templates

---

riocli/hwil/ssh.py

The VM-backed devices don't use externally routable "static_ip". This PR switches to "ip_address" field for `rio hwil ssh` command.

fix(hwil): fix ssh for vm-backed devices
